services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FaceRecognition:
        arguments:
            $pythonServiceUrl: '%env(FACE_RECOGNITION_SERVICE_URL)%'

    App\Service\QrCode:
        arguments:
            $projectDir: '%kernel.project_dir%'